### ISSUE TITLE
Clarification on econd

### ISSUE THREAD

**Issue by Necolangot** [OUCompilers/cs4100-sp20#3]
In both https://github.com/OUCompilers/cs4100-sp20/blob/master/doc/codegen.md and https://github.com/OUCompilers/cs4100-sp20/blob/master/doc/ir.md, it is unclear what type of object econd is. By evaluation, it is '==' followed by two expressions, however, the problem lies that if it itself is evaluated as an expression itself it will create shift/reduce errors, and is hard to figure out with the current BNF without evaluating the .s examples

Thus, I'd like to request that econd be added to the BNF in either document or other examples for clarification for future classes since the econd type is vital to many functions

**Comment by gstew5** [comment]
`econd` in `(cond econd e1 e2)` is an arbitrary expression that's expected to have type bool. Thus the following are all valid:
```
Examples:
(cond (== 3 4) true false) //econd = (3 4)
(cond true 1 2) //econd = true
(cond (cond false 0 1) 7 8) //econd = (cond false 0 1)
```
Does this help clarify?
